
@extends('layouts.main')
@section('main-container')

   
    <!--============================== Breadcumb============================== -->
    <div class="breadcumb-wrapper " data-bg-src="{{ url('assets/img/breadcumb/breadcumb-bg.jpg')}}">
        <div class="container">
            <div class="breadcumb-content">
                <h1 class="breadcumb-title">About Us</h1>
                <ul class="breadcumb-menu">
                    <li><a href="{{ url('/') }}">Home</a></li>
                    <li>About Us</li>
                </ul>
            </div>
        </div>
    </div>
   <div class="container mt-5 mb-5 pt-5 pb-5">
       <div class="row">
           <div class="col-12">
               <h3>Terms Of Use</h3>
              <p>These Terms of Use govern your use of the Service. The “Service” is the website located at www.JUSTISCALL.com (the “Website”), which is operated by HardisonHealth, LLC and its subsidiaries and affiliates (together, JUSTISCALL, “we,” and “us”), and the services available through the Website[JW1] [JW2] [JW3] , including the services of health care providers employed by or contracted with JUSTISCALL of California, Inc. or its affiliated medical practices (“Providers”). The Service is a platform individuals may use to manage their health and receive email, telephone and telecommunications-enabled care from physicians and other health care professionals employed by or contracted with the Providers. By accessing and/or using the Service you agree to be bound by these Terms of Use (this “Agreement”), whether or not you register as a member of JUSTISCALL (“Member”). If you wish to become a Member and make use of the JUSTISCALL service, please read this Agreement.</p>
           <p>CAREFULLY READ THE TERMS AND CONDITIONS OF THIS AGREEMENT BEFORE USING THE WEBSITE OR SERVICE. USING THE WEBSITE OR SERVICE INDICATES YOUR ACCEPTANCE OF THESE TERMS AND CONDITIONS.</p>
           <p>THE SITE IS NOT INTENDED FOR USE IN A MEDICAL EMERGENCY OR IN CASE OF AN URGENT HEALTHCARE NEED.</p>
           <p>This Agreement provides that all disputes between you and JUSTISCALL with respect to your use of the Service will be resolved by BINDING ARBITRATION, to the fullest extent permitted under applicable law. YOU AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under this contract, except for matters that may be taken to small claims court, to the fullest extent permitted under applicable law. Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury, and your claims cannot be brought as a class action, to the fullest extent permitted under applicable law. Please review Section 18 (“Arbitration of Disputes”) for the details regarding your agreement to arbitrate any disputes with JUSTISCALL.</p>
           <h2>1.Acceptance Of Terms Of Use Agreement.</h2>
           <p>(a) Electronic Agreement. This Agreement is an electronic contract that sets out the legally binding terms of your use of and/or your membership in the Service. This Agreement may be modified by JUSTISCALL from time to time. If a change to this Agreement materially modifies your rights or obligations, we will notify you of the modified Agreement by email to the address you provided in your user profile and/or in a notification in the Service or on our website. Material modifications will be effective upon your acceptance of such modified Agreement or upon your continued use of the Service after we send or post our notification of the changes, whichever is earlier. Other modifications are effective upon publication. This Agreement incorporates by reference JUSTISCALL Notice of Privacy Practices and any notices regarding the Service or policies posted on the Service.</p>
            <p>(b) Format of Agreement. By accessing the Service or becoming a Member, you consent to have this Agreement provided to you in electronic form. You may request a non-electronic copy of this Agreement at any time. To receive a non-electronic copy of this Agreement, please send an e-mail to info@JUSTISCALL.com or a letter and self-addressed stamped envelope to: JUSTISCALL, 650 5th Street Suite 405, San Francisco, CA 94107.</p>    
            <p>(c) Withdrawing Your Consent. You have the right at any time to withdraw your consent to have this Agreement provided to you in electronic form. To withdraw your consent, please send an email to info@JUSTISCALL.com or a letter and self-addressed stamped envelope to: JUSTISCALL, 650 5th Street Suite 405, San Francisco, CA 94107. Should you choose to withdraw your consent to have this Agreement provided to you in electronic form, we will discontinue your then-current username and password, and you will not have the right to use the Service unless, and until, we issue you a new username and password. Your withdrawal of consent will not affect the legal validity or enforceability of the Agreement provided to, and electronically signed by, you prior to the effective date of your withdrawal.</p>
           <h2>2.Eligibility And Acknowledgment.</h2>
           <p>By using the Service, you acknowledge and agree that (a) the Provider services are provided at the sole discretion of the Providers; (b) the Service is limited to providing access to Providers for the diagnosis and treatment of only non-emergent medical conditions appropriate for diagnosis and treatment using email, telephone and/or telecommunications; (c) accessing the Service from a jurisdiction other than a jurisdiction which JUSTISCALL operates is prohibited, and you confirm that you are physically located in a jurisdiction which JUSTISCALL operates when you request to use the Service; (d) the cost of the Service and Provider services available through the Service may not be reimbursable by Medicare, Medicaid or any other government health care program, and you agree not to use the Service for any services that are or might be reimbursable by such programs; (e) the cost of the Service and Provider services available through the Service may not be reimbursable by commercial insurers, managed care organizations, preferred provider organizations or other payors, but you may on your own (without assistance from JUSTISCALL) seek reimbursement from any such payor for the cost of use of the Service and Provider services available through the Service; (f) you have not previously been suspended or removed from the Service; (g) your registration and your use of the Service is in compliance with all applicable laws and regulations; (h) you are at least 18 years of age, or you have obtained the consent of your parent or legal guardian to use the Service and you are accompanied by a parent or guardian who can give informed consent on your behalf if you are under the age of 18 at the time of the consultation; and (i) if you are accessing the Service and seeking Provider services on behalf of a child, dependent or other person for whose medical care you are responsible, your approval of the terms of this Use Agreement will bind such other person to these terms.</p>
           <h2>3.Non-Commercial Use By Members.</h2>
           <p>The Service is for the personal use of individual Members only and may not be used in connection with any commercial endeavors. Organizations, companies, and/or businesses may not become Members and should not use the Service for any purpose. All use of the Service may be investigated including, without limitation, to identify illegal or unauthorized use, and appropriate legal action will be taken, including without limitation, civil, criminal, and injunctive action. Your use of the Service is with the permission of JUSTISCALL, which may be revoked at any time, for any reason, in JUSTISCALL sole discretion.</p>
            <h2>4.Charges On Your Billing Account.</h2>
            <p>(a) General. JUSTISCALL bills you through an online account (your “Billing Account”) for use by your Billing Account of the Service and Provider services. You agree to pay JUSTISCALL all charges at the prices then in effect for any use of the Service and Provider services by you or other persons (including your agents) using your Billing Account, and you authorize JUSTISCALL to charge your chosen payment provider (your “Payment Method”) for the fees and costs accrued by your Billing Account for the Service and Provider services. All charges are non-refundable, to the fullest extent permitted under applicable law. You agree to make payment using that selected Payment Method. JUSTISCALL reserves the right to correct any errors or mistakes that it makes even if it has already requested or received payment. If JUSTISCALL changes the charges for the Service and Provider services available through the Service, including by adding additional fees, JUSTISCALL will provide you advance notice of those changes. If you do not accept the changes, JUSTISCALL may discontinue providing the Service to you.</p>
        
            <p>(b) Current Information Required. You must provide current, complete, and accurate information for your Billing Account. You must promptly update all information to keep your Billing Account current, complete and accurate (such as a change in billing address, credit card number, or credit card expiration date), and you must promptly notify JUSTISCALL if your payment method is canceled (e.g., for loss or theft).</p>
           <p>(c) Payment Method. The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer or other provider of your chosen Payment Method (the “Payment Method Provider”). If JUSTISCALL does not receive payment from your Payment Method Provider, you agree to pay all amounts due on your Billing Account upon demand. If you pay any fees with a credit card, JUSTISCALL may seek pre-authorization of your credit card account prior to your purchase to verify that the credit card is valid and has the necessary funds or credit available to cover your purchase.</p>
           <p>(d) Monthly Membership Fee. You may sign up to a subscription (“Subscription”) whereby JUSTISCALL may charge a monthly membership fee (the “Monthly Membership Fee”) for access to certain features of the Service. The Monthly Membership Fee may be modified by notice in accordance with this Agreement. You may have access to the Service through your employers, professional affiliations, or other organizations, and as a result, the Monthly Membership Fee may not apply to you.</p>
            <p>(e) The Monthly Membership Fee covers costs associated with the Subscription, such as the personal services and tools that enhance your healthcare experience on the Service. Such fees are typically not covered by insurance or other health benefits. The services and tools you receive through the Subscription include higher-touch personal services such as insurance and billing navigation, advice on provider selection, specialist booking and referral management, digital tools for easy access to JUSTISCALL services and doctors, as well as lifestyle and wellness offerings. PAYMENT OF THE MONTHLY MEMBERSHIP FEE TO JUSTISCALL IS NOT A REQUIREMENT TO RECEIVE PROVIDER SERVICES ON THE SERVICE. There are options for accessing Provider services on the Service without the Subscription and payment of this fee. To learn more about the Monthly Membership Fee contact us at info@JUSTISCALL.com.</p>
            <p>(f) You are responsible for paying the Monthly Membership Fee when you sign up for the Subscription. The Monthly Membership Fee is likely not a covered benefit under health insurance plans or other healthcare benefit plans such as the Health Saving Account or Flexible Spending Account. As a result, you acknowledge that you may not be able to submit the Monthly Membership Fee for coverage under your insurance or benefit plan, and as such, you are obligated to pay the Monthly Membership Fee.</p>
           <p>(g) For your Subscriptions, JUSTISCALL will charge your Monthly Membership Fee to your designated billing account. You agree to make the payment using your chosen payment method. IF YOUR ACCOUNT IS SUBJECT TO THE MONTHLY MEMBERSHIP FEE, YOU AUTHORIZE JUSTISCALL TO CHARGE YOUR CHOSEN PAYMENT METHOD THE MONTHLY MEMBERSHIP FEE AT THE TIME OF INITIAL PAYMENT AND AS A RECURRING CHARGE FOR EACH MONTHLY RENEWAL ON A GOING FORWARD BASIS, UNTIL YOU CANCEL. YOU MUST CANCEL YOUR MEMBERSHIP BEFORE IT RENEWS TO AVOID BEING CHARGED THE MONTHLY MEMBERSHIP FEE FOR THE NEXT MONTH. YOU CAN CANCEL YOUR MEMBERSHIP AT ANY TIME BY CONTACTING JUSTISCALL AT info@JUSTISCALL.com. IF YOU CANCEL YOUR MEMBERSHIP AND YOUR SUBSCRIPTION TERM HAS NOT EXPIRED, YOU MAY CONTINUE TO USE THE SERVICES UNTIL THE END OF YOUR THEN-CURRENT MEMBERSHIP TERM AND YOUR MEMBERSHIP WILL NOT BE RENEWED AFTER YOUR THEN-CURRENT TERM EXPIRES. HOWEVER, YOU WONT BE ELIGIBLE FOR A PRORATED REFUND OF ANY PORTION OF THE MONTHLY MEMBERSHIP FEE PAID FOR THE THEN-CURRENT MEMBERSHIP PERIOD. If you use the Service to update or cancel any existing authorized one-time or recurring payment, it may take several business days for the update or cancellation to take effect.</p>
           <p>(h) If the amount to be charged to you varies from the amount you preauthorized (other than due to the imposition or change in the amount of state sales taxes), for example, due to an increase in the Monthly Membership Fee, you have the right to receive, and we will provide, notice of the amount to be charged and the date of the charge at least 30 days before the scheduled date of the transaction. If you do not agree with the new amount in the notice, you may cancel the transaction by contacting JUSTISCALL at info@JUSTISCALL.com.</p>
        <p>(i) ANY FREE TRIAL OR OTHER PROMOTION THAT PROVIDES PAID MEMBER-LEVEL ACCESS TO THE SERVICES MUST BE USED WITHIN THE SPECIFIED TIME OF THE TRIAL. IF YOU DO NOT WISH TO CONTINUE YOUR MEMBERSHIP, YOU MUST CANCEL YOUR TRIAL MEMBERSHIP BEFORE THE END OF THE TRIAL PERIOD IN ORDER TO AVOID BEING CHARGED THE MONTHLY MEMBERSHIP FEE, AS APPLICABLE. IF YOU CANCEL PRIOR TO THE END OF THE TRIAL PERIOD AND ARE INADVERTENTLY CHARGED FOR A MEMBERSHIP, PLEASE CONTACT JUSTISCALL AT info@JUSTISCALL.com FOR A REFUND.</p>
    <h2>5.Account Security.</h2>
    <p>You are solely responsible for maintaining the confidentiality of the username and password that you designate during the registration process, and you are solely and fully responsible for all activities that occur under your username and password. You agree to (a) immediately notify JUSTISCALL} of any loss or unauthorized use of your username or password or any other breach of security related to your account, and (b) ensure that you exit from your account at the end of each session. JUSTISCALL will not be liable for any loss or damage arising from your failure to comply with this provision. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. If you share your computer with others, you may wish to consider disabling any auto-sign in feature if you have linked your JUSTISCALL account to any electronic mail service or other account.</p>   
    <h2>6.Intellectual Property Rights.</h2>
    <p>(a) JUSTISCALL Intellectual Property. JUSTISCALL and/or its licensors are the owner of all right, title, and interest in and to the Service, including all rights to the information, content, design, software code, scripts, database structures, trademarks, copyrights, and other intellectual property included in or utilized by the Service, and any updates thereto (the “JUSTISCALL IP”). JUSTISCALL IP does not include any Content (defined below). JUSTISCALL IP is protected by applicable intellectual property and other laws, including laws governing patents, copyrights, trade secrets, trademarks, and unfair competition.</p>
    <p>(b) License to You. Subject to your ongoing compliance with this Agreement, JUSTISCALL grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Service solely for your personal, non-commercial use for lawful purposes.</p>
    
    <p>(c) Reservation of Rights Not Expressly Granted. JUSTISCALL reserves all rights not expressly granted to you in this Agreement. Except for the limited rights and licenses expressly granted under this Agreement, nothing in this Agreement grants, by implication, waiver, estoppel, or otherwise, to you or any third party any intellectual property rights or other right, title, or interest in or to the JUSTISCALL intellectual property.</p>
    <p>(d) Open Source. The Service may include or incorporate third-party software components that are generally available free of charge under licenses granting recipients broad rights to copy, modify, and distribute such components (“Open Source Components”). Although the Service is provided to you subject to this Agreement, nothing in this Agreement will be deemed to prevent, restrict, or otherwise prevent or restrict you from obtaining such Open Source Components under the applicable third-party licenses or to limit your use of such Open Source Components thereunder.</p>
    <p>(e) Content. Certain features of the Service may permit you or other users (including Providers) to upload content to the Service, including messages, reviews, images, data, text, and other types of information (“Content”) and to publish Content on the Service. You retain any copyrights, moral rights, and any other proprietary rights that you may hold in the Content that you post to the Service.</p>
    
    <p>(f) Limited License Grant to JUSTISCALL. By posting or publishing Content, you grant JUSTISCALL a worldwide, non-exclusive, royalty-free, fully paid, unrestricted right and license (with the right to sublicense) to use, host, store, transfer, display, perform, reproduce, modify, and distribute your Content, in whole or in part, in accordance with our Privacy Policy, in any media formats and through any media channels now known or hereafter developed.</p>
    <p>(g) Limited License Grant to Other Users. By posting or sharing Content with other users of the Service (including Providers), you grant those users a non-exclusive license to access and use that Content as permitted by this Agreement and the functionality of the Service.</p>
    <p>(h) Content Representations and Warranties. You are solely responsible for your Content and the consequences of posting or publishing Content. By posting or publishing Content, you affirm, represent, and warrant that:</p>
     <p>you are the creator and owner of the Content, or have the necessary licenses, rights, consents, and permissions to authorize JUSTISCALL and users of the Service (including Providers) to use and distribute your Content as necessary to exercise the licenses granted by you in this section, in the manner contemplated by the Service, JUSTISCALL, and this Agreement; and your Content, and the use of the Service as contemplated by this Agreement, does not and will not: (x) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (y) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; or (z) cause JUSTISCALL to violate any law or regulation, including laws related to the privacy of personal or health information. (i) Content Disclaimer. JUSTISCALL is under no obligation to monitor, edit, or control Content that you or other users (including Providers) post or publish, and will not be in any way responsible or liable for Content or any failure to review or act upon Content. JUSTISCALL may, however, at any time and without prior notice, screen, remove, edit, or block any Content that in our sole judgment violates this Agreement or is otherwise objectionable. To the fullest extent allowed under applicable law, you agree to waive, and do waive, any legal or equitable right or remedy you have or may have against JUSTISCALL with respect to Content. We expressly disclaim any and all liability in connection with Content, to the fullest extent allowed under applicable law. If notified by a user or content owner that Content allegedly does not conform to this Agreement, we may investigate the allegation and determine in our sole discretion whether to remove the Content, which we reserve the right to do at any time and without notice.</p>
<p>(j) You hereby consent to JUSTISCALL engagement of third parties (including JUSTISCALL affiliates and subsidiaries) to perform, provide, or support the performance or provision of, all or any portion of the Service and they may receive access to your Content.</p>


<h2>7.Prohibited Activities.</h2>
<p>JUSTISCALL reserves the right to investigate and terminate your use and/or membership if you have misused the Service, or behaved in a way which could be regarded as inappropriate or engaged in conduct that is unlawful or illegal. The following is a partial list of the type of actions that you may not engage in (or encourage others to engage in) with respect to the Service:</p>
<p>You will not express or imply that any statements you make are endorsed by JUSTISCALL without our specific prior written consent.</p>
<p>You will not use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, “data mine”, or in any way reproduce or circumvent the navigational structure or presentation of the Service or its contents.</p>
<p>You will not violate, or encourage others to violate, any right of a third party, including by infringing or misappropriating any third party intellectual property right, or violating any third party privacy right.</p>
<p>You will not interfere with or disrupt the Service or the servers or networks connected to the Service, including any security or access control mechanism.</p>
    <p>You will not post, email or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment.</p>
 
<p>You will not forge headers or otherwise manipulate identifiers in order to disguise the origin of any information transmitted through the Service.</p>
<p>You will not “frame” or “mirror” any part of the Service, without JUSTISCALL prior written authorization. You will not use meta tags or code or other devices containing any reference to JUSTISCALL or the Service in order to direct any person to any other web site for any purpose.</p>
<p>You will not modify, adapt, sublicense, translate, sell, reverse engineer, decipher, decompile or otherwise disassemble or modify any portion of the Service or any software used on or for the Service or cause or enable others to do so.</p>
<p>You will not use the Service if you are prohibited under applicable law from using the Service.</p>
<p>You will not conduct activities that may be harmful to others or that could damage JUSTISCALL reputation.</p>
<p>You will not post, upload, or distribute marketing or advertising links or content, or any User Content or other content that is unlawful, defamatory, libelous, inaccurate, or that a reasonable person could deem to be objectionable, profane, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate.</p>
<p>You will not make any unsolicited offer or advertisement to another user of the Service or attempt to collect personal information or other information about another user or third party without their consent.</p>
<p>You will not perform any fraudulent activity including impersonating any person or entity, claiming a false affiliation or accreditation, accessing any other Service account without permission, or falsifying your account registration information.</p>
<p>You will not modify, translate, or create derivative works, adaptations or compilations of, or based on, the Service or part thereof, or use, copy or reproduce the Service or any part thereof other than as expressly permitted in this Agreement;</p>
<p>You will not use the Service if you are the subject of U.S. sanctions or of sanctions consistent with U.S. law imposed by the governments of the country where you are using the Services. You must comply with all U.S. or other export and re-export restrictions that may apply to goods, software, technology, and services;</p>
<p>You will not assign, sublicense, lease, sell, grant a security interest in, or otherwise transfer the access granted under this Agreement or any JUSTISCALL IP (as defined in Section 6) or any right or ability to view, access, or use any JUSTISCALL IP; or

You will not attempt to do any of the acts described in this Section 7, or assist or permit any person in engaging in any of the acts described in this Section 7.</p>



<h2>8.JUSTISCALL Consent.</h2>
<p>By completing your registration through the Service, you give permission to the Providers to provide you with medical care. You may withdraw this consent at any time by no longer seeking care from JUSTISCALL Providers or by providing notice to JUSTISCALL of such withdrawal. JUSTISCALL JUSTISCALL or telemedicine services involves the delivery of healthcare services using electronic communications, information technology, or other means between a medical provider and a client who are not in the same physical location. Telemedicine may be used for diagnosis, treatment, follow-up and/or client education, and may include, but is not limited to:</p>
<p>Electronic transmission of medical records, photos/images, personal health information, or other data between a client and a medical provider; Interactions between a client and medical provider via audio, video, and/or asynchronous data communications; and Use of output data from medical devices, sound, and video files. By creating a Member account and accessing the Service (including the Provider services), you acknowledge and agree to this JUSTISCALL Consent and a record of such acknowledgement will be retained in the medical record of the Provider and professional entity providing such services through the Service.”</p>
<h2>9.Modifications To Or Termination Of The Service.</h2>
<p>JUSTISCALL reserves the right to modify or discontinue the Service (or any portion thereof) at any time (including by limiting or discontinuing certain features of the Service), temporarily or permanently, without notice to you. To the fullest extent permitted under applicable law, we will have no liability whatsoever on account of any change to the Service or any suspension or termination of your access to or use of the Service. Upon the termination of your account, any aspect of the Service, or this agreement for any reason, JUSTISCALL may at its option delete any data and/or Content you submitted through the Service.</p>
<h2>10.Copyright And Trademark.</h2>
<p>You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. The trade names, trademarks, service marks, logos, and slogans contained in the Service are the trade names, trademarks, service marks, logos and slogans of JUSTISCALL (each a “Mark” and collectively the “Marks”). You are not authorized to use any Mark in any advertisement, publicity or in any other commercial manner without our prior written consent. The trade names, trademarks, service marks, logos and slogans contained in the Service that are not our Marks are the trade names, trademarks, service marks, logos and slogans of their respective owners.</p>

<h2>11.Privacy.</h2>
<p>Use of the Service is also governed by our Notice of Privacy Practices and privacy policy, copies of which may be found on the Service. You authorize JUSTISCALL to use and publish any comments you choose to share about the Service, including comments shared in client satisfaction surveys, unless otherwise specified. JUSTISCALL will only publish comments using your first name. If you choose to share your protected health information over email, telephone or video communications you acknowledge that such email, telephone or video communications may not be encrypted and/or may not be a secure method of communication, and you assume the risk of such unsecured communications.</p>
<h2>12.Healthcare Disclaimers Regarding The Service.</h2>
<p>YOU AGREE THAT YOUR USE OF THE SERVICE IS AT YOUR OWN RISK. YOU ACKNOWLEDGE THAT THE SERVICE IS NOT INTENDED FOR USE IN A MEDICAL EMERGENCY OR IN CASE OF AN URGENT HEALTHCARE NEED, AND AGREE THAT YOU WILL SEEK CARE ELSEWHERE IN THE EVENT OF A MEDICAL EMERGENCY OR URGENT HEALTHCARE NEED (SUCH AS BY CALLING 911 in the United States). The Service is not a replacement for your primary care physician or annual office check-ups. The Service is not an online pharmacy, and Providers do not prescribe certain elective medications, narcotic pain relievers, or drugs listed as controlled substances by the U.S. Drug Enforcement Agency. You agree that any prescription obtained through the Service from a Provider will be used only for its intended use. JUSTISCALL does not guarantee that a specific medication will be prescribed if requested.</p>
<h2>13.Disclaimers Regarding The Service.</h2>
<p>The Service and all information and content available on the Service is provided “AS-IS” without warranties of any kind, whether express, implied. THE JUSTISCALL Group DISCLAIM, AND YOU HEREBY EXPRESSLY WAIVE, ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, RELATING TO the Service AND ALL MATERIALS, PRODUCTS, AND CONTENT AVAILABLE THROUGH the Service, INCLUDING: (A) ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; (B) ANY WARRANTY ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE; AND (C) ANY WARRANTY AS TO WHETHER THE DATA OR OTHER INFORMATION OR CONTENT AVAILABLE THROUGH OR TRANSMITTED BY THE SERVICE IS TRUE, COMPLETE OR ACCURATE.</p>
<p>THE JUSTISCALL Group DOES NOT WARRANT THAT the Service OR ANY PORTION OF the Service, OR ANY MATERIALS OR CONTENT OFFERED THROUGH the Service, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS, AND DO NOT WARRANT THAT ANY OF THOSE ISSUES WILL BE CORRECTED. JUSTISCALL cannot guarantee and does not promise any specific results from use of the Service.</p>
<p>THE JUSTISCALL GROUP is not responsible for any incorrect or inaccurate content or information posted on the Service or in connection with the Service, whether caused by users of the Service, Members or by any of the equipment or programming associated with or utilized in the Service. THE JUSTISCALL GROUP is not responsible for the conduct, whether online or offline, of any user or Member of the Service or any Provider available through the Service. THE JUSTISCALL GROUP assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, user, Member, or Provider communications. THE JUSTISCALL GROUP is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, or failure of email on account of technical problems or traffic congestion on the Internet or at any web site or combination thereof. Under no circumstances will THE JUSTISCALL GROUP or any of THEIR advertisers, promoters or distribution partners be responsible for any loss or damage, including personal injury or death, resulting from anyone use of the Service, any content posted on the Service or transmitted to Members, or any interactions among users or Members of the Service or Providers available through the Service, whether online or offline.</p>


<p>In addition to the preceding paragraphs and other provisions of this Agreement, any advice that may be posted on or communicated in connection with the Service by anyone (including, without limitation, Providers) is for informational purposes only and is not intended to replace or substitute for any professional financial, medical, legal, or other advice. THE JUSTISCALL GROUP makes no representations or warranties and expressly disclaims any and all liability concerning any treatment, action by, or effect on any person following the information offered or provided within or through the Service.</p>
<p>THE ABOVE PARAGRAPHS APPLY TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW. SOME JURISDICTIONS MAY PROHIBIT A DISCLAIMER OF WARRANTIES, IN PARTICULAR A DISCLAIMER OF WARRANTIES PROVIDED OR IMPLIED BY LAW, AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</p>

<h2>14.Links.</h2>

<p>The Service or third parties may provide links to web sites operated by third parties. These links are provided solely for convenience and reference purposes only. The inclusion of any such link does not imply that we endorse the content of any web site to which the Service provides a link, nor are we liable for your reliance on or use of any information or materials contained in them.</p>

<h2>15.User Feedback</h2>
<p>You may be asked to provide input, suggestions, and feedback on the Service and your JUSTISCALL experience (“Feedback”). This Feedback is always optional and your choice. If you choose to provide Feedback, then you hereby grant JUSTISCALL an unrestricted, perpetual, irrevocable, non-exclusive, fully-paid, royalty-free right to exploit such Feedback in any manner and for any purpose, including to improve the Service and create other products and services. This feedback may be hosted and stored at a third party web site. You agree to not provide any personally identifiable information when providing feedback.</p>

<h2>16.Limitation Of Liability</h2>
<p>IN NO EVENT WILL THE JUSTISCALL GROUP BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING DAMAGES FOR INCREASED COSTS, DIMINUTION IN VALUE OR LOST BUSINESS, PRODUCTION, REVENUES, OR PROFITS, GOODWILL, REPUTATION, OR ANY OTHER INTANGIBLE LOSS) ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, the Service OR ANY MATERIALS OR CONTENT AVAILABLE ON OR THROUGH the Service, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY MEMBER OF THE JUSTISCALL GROUP HAS BEEN INFORMED OF THE POSSIBILITY OF DAMAGE.</p>
<p>THE AGGREGATE LIABILITY OF THE JUSTISCALL GROUP TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF OR ANY INABILITY TO USE ANY PORTION OF the Service, or content or information available through the Service (including any information received from Providers) OR OTHERWISE UNDER THIS AGREEMENT, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED TO the amount paid, if any, by you to JUSTISCALL for the Service during the term of membership, TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW.</p>
<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES. ACCORDINGLY, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. FURTHERMORE, NOTHING IN this AGREEMENT LIMITS OR EXCLUDES ANY LIABILITY THAT CANNOT BE LIMITED OR EXCLUDED BY LAW.</p>


<p>EACH PROVISION OF THIS AGREEMENT THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS INTENDED TO AND DOES ALLOCATE THE RISKS BETWEEN THE PARTIES UNDER this AGREEMENT. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF this AGREEMENT. THE LIMITATIONS IN THIS SECTION 16 WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>

<h2>17.Indemnity By You.</h2>
<p>You agree to indemnify and hold JUSTISCALL, its subsidiaries, affiliates, officers, directors, consultants, agents, and other partners and employees (together, the “JUSTISCALL Group”), harmless from any loss, liability, claim, or demand, including reasonable attorney fees, arising out of or in any way connected with: (a) your access to, use of, or alleged use of the Service; (b) your failure to comply with applicable laws and regulations; and/or (c) your breach of any portion of this Agreement and/or any breach of your representations and warranties set forth above; (c) your violation of any third-party right, including any intellectual property right or publicity, confidentiality, other property, or privacy right; (d) any dispute or issue between you and any third party (including any Provider); and (e) fraud, intentional misconduct, criminal acts, gross negligence, or negligence committed by you.</p>
<h2>18.Arbitration Of Disputes.</h2>

<p>(a) It is understood that any dispute between you and the JUSTISCALL Group as to medical malpractice, that is as to whether any medical services rendered under this Agreement were unnecessary or unauthorized or were improperly, negligently, or incompetently rendered, will be determined by submission to arbitration as provided by California law, and not by a lawsuit or resort to court process except as California law provides for judicial review of arbitration proceedings. Both parties to this contract, by entering into it, are giving up their constitutional right to have such dispute decided in a court of law before a jury, and instead are accepting the use of arbitration.</p>
<p>(b) You understand and agree that this agreement to arbitrate binds you and anyone else (including, without limitation, a spouse or heirs and any children, whether born or unborn at the time of the occurrence giving rise to any claim) who may have a claim arising out of or related to all treatment or services provided by the JUSTISCALL Group, Providers, and others employed or engaged by JUSTISCALL. This includes, but is not limited to, all claims for monetary damages exceeding the jurisdictional limit of the small claims court, including, without limitation, suits for loss of consortium, wrongful death, emotional distress, or punitive damages. You further understand and agree that if you sign this Agreement on behalf of some other person for whom you have responsibility, then, in addition to myself, such person(s) will also be bound by this agreement to arbitrate, along with anyone else who may have a claim arising out of the treatment or services rendered to that person. You also understand and agree that this agreement to arbitrate relates to claims against any of the JUSTISCALL Group, Providers, or others employed or engaged by the JUSTISCALL Group and any consenting substitute physician, as well as a physician partners, associates, association, corporation or partnership, and the employees, agents, and estates of any of them. You also hereby consent to the intervention or joinder in the arbitration proceeding of all parties relevant to a full and complete settlement of any dispute arbitrated under this Agreement, as set forth in the Medical Arbitration Rules of the California Medical Associations and the California Hospital Associations (the “Rules”).</p>
<p>(c) You agree that the arbitrators have the same immunity from civil liability as that of a judicial officer when acting in the capacity of arbitrator under this agreement to arbitrate. This immunity shall supplement, not supplant, any other applicable statutory or common law.</p>
<p>(d) YOU UNDERSTAND THAT YOU DO NOT HAVE TO SIGN THIS AGREEMENT TO ARBITRATE IN ORDER TO RECEIVE THE SERVICES OF JUSTISCALL OR ITS EMPLOYED OR ENGAGED PROVIDERS, AND THAT IF YOU DO SIGN THIS AGREEMENT TO ARBITRATE AND CHANGE YOUR MIND WITHIN 30 DAYS OF TODAY, THEN YOU MAY CANCEL THIS AGREEMENT TO ARBITRATE BY GIVING WRITTEN NOTICE TO JUSTISCALL WITHIN 30 DAYS OF THE DATE OF YOUR SIGNATURE BELOW STATING THAT YOU WANT TO WITHDRAW FROM THE ARBITRATION PROVISIONS OF THIS AGREEMENT. SHOULD YOU CHOOSE TO WITHDRAW FROM THE ARBITRATION PROVISIONS OF THIS AGREEMENT, ALL OTHER PROVISIONS OF THIS AGREEMENT WILL REMAIN IN FULL FORCE AND EFFECT.</p>
<p>(e) On behalf of yourself and all others bound by this agreement to arbitrate as set forth in Paragraph 18(b), agreement is hereby given to be bound by the Medical Arbitration Rules of the California Medical Associations and the California Hospital Associations, as they may be amended from time to time, which rules are hereby incorporated into this Agreement.

</p>
<p>(f) To the fullest extent permitted under applicable law, no action arising out of, in connection with, or relating to the Agreement shall be brought by you more than one (1) year after the accrual of the cause of action. This period shall not be extended for any reason, except by the written consent of both parties. All statutes or provisions of law which would toll or otherwise affect the running of the period of limitation are hereby waived, and no such statute or provision of law shall operate to extend the period limited in this paragraph, to the fullest extent permitted under applicable law.</p>
<h2>19.Jurisdiction And Choice Of Law.</h2>
<p>If there is any dispute arising out of the Service, you expressly agree that any such dispute shall be governed by the laws of the State of California, without regard to its conflict of law provisions. If a lawsuit or court proceeding is permitted under this Agreement, then you and JUSTISCALL agree to submit to the exclusive jurisdiction of the state courts and federal courts located within San Francisco County, California for the purpose of litigating any dispute, and you hereby consent to the personal jurisdiction and venue thereof.</p>
<h2>20.No Third Party Beneficiaries.</h2>
<p>You agree that, except as otherwise expressly provided in this Agreement, there shall be no third-party beneficiaries to this Agreement.
</p>
<h2>21.Acknowledgment Of Terms And Electronic Signature.
</h2>
<p>You certify that you have read, accept, and hereby consent to the terms of this Agreement, and your acceptance of these terms constitutes your electronic signature to this Agreement. You agree that you may be sent electronic notices to the email address provided during your registration for the Service. Any notice sent to that email address will be effective once delivered, regardless of whether or not you actually received the notice or choose to read it. This Agreement constitutes the sole agreement between you and JUSTISCALL for your use of the Service, and any further statements or inducements, oral or written, not contained in this Agreement shall not bind either you or JUSTISCALL. Any of the terms of this Agreement which are invalid or unenforceable shall be ineffective to the extent of such invalidity or unenforceability, without rendering invalid or unenforceable any of the remaining terms of this Agreement.

</p>
<h2>22.Referral Policy.
</h2>
<p>Personal invite links should only be used for personal and non-commercial purposes. This means that you are permitted to share your invite link with your personal connections via email, Twitter feeds, Facebook pages, personal blogs, etc. where you are the primary content owner. However public distribution on web sites where you are a contributor but not the primary content owner (e.g., Wikipedia, coupon web sites) is not allowed and would violate this Agreement. Promoting your referral code via Search Engine Marketing (e.g., AdWords/Yahoo/Bing) is also not allowed and would violate this Agreement.

<p>
<p>JUSTISCALL reserves the right to suspend your account and/or revoke any and all referral credits at any time if JUSTISCALL determines in its sole discretion they were earned inappropriately or in violation of this Agreement.
JUSTISCALL Referral Program.
</p>
<p>Existing customers (“Referrer”) who refer friends and family as new customers (“Customer”) to JUSTISCALL, may be eligible to receive a Referrer Credit benefit and Customer will receive a Referee Credit. Customer must sign up using the unique link (“Link”) provided to them by the Referrer. Personal invite links should only be used for personal and non-commercial purposes. This means that you are permitted to share your invite link with your personal connections via email, Twitter feeds, Facebook pages, personal blogs, etc. where you are the primary content owner. However public distribution on web sites where you are a contributor but not the primary content owner (e.g., Wikipedia, coupon web sites) is not allowed and would violate this Agreement. Promoting your referral code via Search Engine Marketing (e.g., AdWords/Yahoo/Bing) is also not allowed and would violate this Agreement. JUSTISCALL reserves the right to suspend your account and/or revoke any and all referral credits at any time if JUSTISCALL determines in its sole discretion they were earned inappropriately or in violation of this Agreement.

</p>
<p>Referrer will only receive Referrer Credits only if both Referrer and Customer are located in the United States. Customer will receive Referee Credits when they sign up through the Link and meet the requirements as indicated in the offer. JUSTISCALL reserves the right to deactivate or invalidate any Referrer Credits or Referee Credits obtained by either Customer or Referrer in violation of the requirements indicated in the offer. Credit amounts will be stated in Referrer JUSTISCALL account and in the offer received by Customer. Customer will be disqualified and will not receive Credits if JUSTISCALL determines that Customer has previously created a JUSTISCALL account. JUSTISCALL reserves the right to withhold or invalidate Referrer Credits or Referee Credits obtained through the JUSTISCALL Referral Program if JUSTISCALL determines or believes that the Referrer Credits or Referee Credits were received through error, fraudulent, illegal, or in violation of these terms and conditions or any other applicable agreement between you and JUSTISCALL.

</p>
<p>Referrer Credits will be applied automatically after Customer pays for their first month of membership. Referee Credits will be applied automatically at sign up via the link provided by Referrer. If Referrer cancels their membership and earns Referee Credits after cancellation, the Referee Credits will not be applied to the Referrer account. Referrer Credits or Referee credits may only be redeemed through JUSTISCALL.com or on the JUSTISCALL app with the latest version. Referrer Credits or Referee Credits cannot be redeemed for cash or cash equivalent. Referrer Credits and Referee Credits are not transferable and may not be auctioned, traded, bartered, or sold, and they may not be used in conjunction with select promotions. JUSTISCALL reserves the right to withhold or invalidate Referrer Credits and Referee Credits obtained through the JUSTISCALL Referral Program if JUSTISCALL determines or believes they were received through error, fraudulent, illegal, or in violation of these terms and conditions or any other applicable agreement between you and JUSTISCALL.

</p>
<h2>23. Consent To Communications And Monitoring/Recording Of Voice Calls And Text Messages Made Through The Service.
</h2>
<p>By providing JUSTISCALL with your contact information and using the Service, you agree to receive communications, including via e-mail and phone calls (including text messages and calls made using an autodialer or prerecorded voice message), from or on behalf of JUSTISCALL at the email address or telephone number you provided even if that number is on a National or State Do Not Call List. These calls and messages may be for informational purposes, such as to provide you with the information or consultation you requested. Standard text messaging and telephone minute charges applied by your cell phone carrier will apply.

</p>
<p>JUSTISCALL and its service providers on its behalf may, without further notice or warning and in our discretion, monitor and/or record video and voice calls and text message-based communications for our business purposes, such as quality assurance and training purposes and to protect our rights and the rights of others, and you hereby consent to such monitoring and recording.

</p>
<p>You may opt-out of receiving text (SMS) messages from JUSTISCALL at any time by texting the word STOP to from the mobile device receiving the messages. You understand and agree that you may continue to receive communications while JUSTISCALL processes your opt-out request, and you may also receive a communication confirming the receipt of your opt-out request. You acknowledge that opting out of receiving text (SMS) messages may impact your use of the Services.

</p>
<h2>24.Termination Of Your Access To The Service.
</h2>
<p>You may terminate your use of the Services at any time by not using the Services any more. If you wish to terminate your membership, you can do so by contacting JUSTISCALL via email at info@JUSTISCALL.com. If you terminate your membership, your membership will remain active until the end of your then-current membership period. JUSTISCALL may in its sole discretion terminate your Member account on the Service or suspend or terminate your access to the Service at any time for any reason or no reason by sending notice to you at the email address you provided or otherwise contacting you or posting a notice on the Services (unless JUSTISCALL terminates your access due to your breach of this Agreement). If you violate any provision of this Agreement, your permission from JUSTISCALL to use the Service will terminate automatically. If we terminate your use of the Services because you have breached this Agreement or any other agreement you have entered into with us, you will not be entitled to any refund of the paid Monthly Membership Fee. We are not required to provide you with notice prior to terminating your use of the Services or a reason for such termination. If we terminate your access to the Services other than due to your breach of this Agreement or any other agreement you have entered into with us, you will be entitled to a pro rata refund of the Monthly Membership Fee that you paid for the remainder of your membership period. Upon the termination of your account, any aspect of the Service, or this agreement for any reason, JUSTISCALL may at its option delete any data and/or Content you submitted through the Service.

</p>
<h2>25.Force Majeure.
</h2>
<p>To the fullest extent permitted under applicable law, JUSTISCALL will be excused from performance under this Agreement for any period that it is prevented from or delayed in performing any obligations pursuant to this Agreement, in whole or in part, as a result of a Force Majeure Event. For purposes of this section, “Force Majeure Event” means an event or series of events caused by or resulting from any of the following: (a) weather conditions or other elements of nature or acts of God; (b) acts of war, acts of terrorism, insurrection, riots, civil disorders or rebellion; (c) quarantines or embargoes, (d) labor strikes; (e) telecommunications, network, computer, server or Internet disruption or downtime; (f) unauthorized access to JUSTISCALL information technology systems by third parties; or (g) other causes beyond the reasonable control of JUSTISCALL.

</p>

<h2>26.General.
</h2>
<p>This Agreement, together with the JUSTISCALL Notice of Privacy Practices and any other agreements expressly incorporated by reference into this Agreement, are the entire and exclusive understanding and agreement between you and JUSTISCALL regarding your use of the Service. Except as expressly permitted above, this Agreement may be amended only by a written agreement signed by authorized representatives of all parties to these Terms. You may not assign or transfer this Agreement or your rights under this Agreement, in whole or in part, by operation of law or otherwise, without our prior written consent. We may assign this Agreement at any time without notice or consent. The failure to require performance of any provision will not affect our right to require performance at any other time after that, nor will a waiver by JUSTISCALL of any breach or default of this Agreement, or any provision of this Agreement, be a waiver of any subsequent breach or default or a waiver of the provision itself. Use of section headers in this Agreement is for convenience only and will not have any impact on the interpretation of any provision. If any part of this Agreement is held to be invalid or unenforceable, the unenforceable part will be given effect to the greatest extent possible, and the remaining parts will remain in full force and effect. Upon termination of this Agreement, Sections 3, 5, 6(a), 6(c) through 6(j), 7, and 9-27 along with the JUSTISCALL Privacy Policy and any other accompanying agreements, will survive.

</p>
<p>I agree to comply with this Agreement, on behalf of myself and on behalf of any other person on whose behalf I am seeking medical care. I understand and agree that if I fail to comply with the terms of the Agreement, I may be prohibited from using the Service, and I will hold JUSTISCALL harmless from any liability arising from my failure to comply. I hereby certify that I am at least 18 years of age and possess the legal right and ability to enter into this Agreement under the name in which I have registered to use the Service. I further certify that I am physically present in a state which JUSTISCALL operates at the time that I am accessing the Service. I understand and acknowledge that my ability to access the Service is conditional upon the abovementioned criteria of my certification of age, legal authority, and physical presence in a state which JUSTISCALL operates at the time that I access the Service, and that the Providers rely upon this certification in order to interact and facilitate health care services with me.

</p>
<br>
<p>NOTICE: BY SIGNING THIS AGREEMENT I AM AGREEING TO HAVE ANY ISSUE OF MEDICAL MALPRACTICE DECIDED BY NEUTRAL ARBITRATION AND I AM ARE GIVING UP MY RIGHT TO A JURY OR COURT TRIAL. SEE PARAGRAPH 18 OF THIS AGREEMENT.

</p>
<p>I HAVE READ THIS AGREEMENT AND AGREE TO ALL OF THE PROVISIONS CONTAINED ABOVE.

</p>
</div>
       </div>
   </div>
  
   <!--********************************Code End Here ******************************** -->
    <!-- Scroll To Top -->
    <div class="scroll-top"> <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" style="transition: stroke-dashoffset 10ms linear 0s; stroke-dasharray: 307.919, 307.919; stroke-dashoffset: 307.919;"> </path>
        </svg> </div>

@endsection